version: 2
updates:
  - package-ecosystem: npm
    target-branch: 'next-release'
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    # commit-message:
    #   prefix: '[skip netlify]'
