[build]
  #ignore = "git log -1 --pretty=%B | grep dependabot"  # ignore all PRs opened by `dependabot` (with last commit made by `dependabot`)
  
  [context.branch-deploy.environment]
  NODE_ENV = "development"
  
[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "wmca-digital"
    sentryProject = "wmn-disruption-manage"
