[build]
  #ignore = "git log -1 --pretty=%B | grep dependabot"  # ignore all PRs opened by `dependabot` (with last commit made by `dependabot`)

[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "wmca-digital"
    sentryProject = "wmn-disruption-manage"

# Use staging for branch deploys for develop
# So that dummy data from testing does not enter live DB
[context.develop]
environment = { REACT_APP_API_HOST="https://rtccdisruptions6zqwajo6s.azurewebsites.net/", REACT_APP_AUTOCOMPLETE_API="https://wmca-api-portal-staging.azure-api.net", REACT_APP_AUTOCOMPLETE_API_KEY="0d4cca4a2c5d40c3bfbbfe45d1bbf294", REACT_APP_DISRUPTION_SIGN_UP_URL="https://next-release--disruption-sign-up.wmnetwork.co.uk/" }